# Generated by Django 4.0.6 on 2022-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(choices=[('W', 'Working'), ('N', 'Not Working')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=1, null=True),
        ),
    ]
