# Generated by Django 4.0.6 on 2022-08-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_card_account_remove_loans_guaranter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.IntegerField(default=0)),
                ('account_Name', models.CharField(max_length=20, null=True)),
                ('savings', models.IntegerField()),
                ('wallet', models.CharField(max_length=20, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_Destination', to='wallet.account')),
            ],
        ),
    ]
