# Generated by Django 4.0.6 on 2022-08-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_Destination', to='wallet.wallet'),
        ),
    ]
