# Generated by Django 4.0.6 on 2022-08-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('phone_Number', models.IntegerField()),
                ('transaction_cost', models.IntegerField()),
                ('active', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_account', to='wallet.account')),
            ],
        ),
    ]
